#!/bin/bash
find -type f -name " *.gif" | rev I cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -ffind -type f -name " *.gif" | rev I cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f

