#!/usr/bin/env bash
# displays Best School 10 times using while loop and on the ninth iteration it prints hi

i=1

while [ "$i" -lt 11 ]; do
  echo "Best School"

# if statement to print Hi in the ninth iteration i = 9
  if [ $i == 9 ]; then
    echo "Hi"
  fi


  ((i++))
done
