#!/usr/bin/env bash
# 4 bad luck, 8 is good luck

i=1

while [ "$i" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ $i == 4 ]; then
    echo "bad luck"
  elif [ $i == 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((i++))
done
