#!/usr/bin/env bash
# 

i=1

while [ "$i" -lt 21 ]; do
  echo $i

   # if 4 bad luck elif 8 good luck
  if [ $i == 4 ]; then
    echo "bad luck from China"
  elif [ $i == 9 ]; then
    echo "bad luck from Japan"
  elif [ $i == 17 ]; then
    echo "bad luck from Italy"
  fi

  ((i++))
done
